### ISSUE TITLE
ajax post request returns err:400

### ISSUE THREAD

**Issue by soosa** [HackBrexit/What-the-fact-frontend#2]
project is temporarily on http://178.62.41.106:8000/api/
post request don't send and keep returning 400 bad request

suspect it is a Cross-Origin issues however I set the permissions in the manifest.json file

**Comment by eddiejaoude** [comment]
I don't think it is a **Cross-origin** issues as this would be returned as that - check the **CORS** settings on the API. 

`400` status code means that the **parameters** being sent are not correct. Is there a **request** example of what the API is expecting for that call?

**Comment by jialutu** [comment]
The data send through via post by the extension has this format:
<QueryDict: {'ie': ['UTF-8#q=chrome extension post request 400 error permission set","user_question":"dd","questionable_fact":" - You have forgotte","user_email":"dd"}'], 'ion': ['1'], '{"questionable_fact_url":"https://www.google.co.uk/webhp?sourceid': ['chrome-instant'], 'espv': ['2']}>

Whereas if using postman and also curl sends like as below:
<QueryDict: {'user_question': ['something'], 'user_email': ['something'], 'questionable_fact': ['something'], 'questionable_fact_url': ['something']}>
[07/Jan/2017 15:53:35] "POST /api/ HTTP/1.1" 201 122
<QueryDict: {'user_question': ['somethingelse'], 'user_email': ['testagain'], 'questionable_fact': ['something'], 'questionable_fact_url': ['test']}>
[07/Jan/2017 15:55:04] "POST /api/ HTTP/1.1" 201 121

**Comment by eddiejaoude** [comment]
Do you have a working `curl` example? or is there documentation for the API that has a `request` example?

**Comment by soosa** [comment]
it is fixed now :) the ajax request did not like JSON format but posted ok when data was string. 
JSON.stringify(data); =>did not work
